INCLUDE     PIOC_INC.ASM

    ORG     0X0000
    DW      0X0000
    JMP     MCU_START
    DW      0X0FFF

MCU_START:
    BS      SFR_PORT_DIR, SB_PORT_DIR0
    BS      SFR_PORT_DIR, SB_PORT_DIR1

loop:
    BS      SFR_PORT_IO, SB_PORT_OUT1
    BC      SFR_PORT_IO, SB_PORT_OUT0
    INC     SFR_DATA_EXCH, F
    NOP
    BC      SFR_PORT_IO, SB_PORT_OUT1
    BS      SFR_PORT_IO, SB_PORT_OUT0
    JMP     loop

    END
